---
version: 2
multicolumn: false
web-width: 600px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/img/img.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/446429/articles/545668/master/folder/figures/img"
    url: "/users/446429/articles/545668/master/file/figures/img/img.png"
