---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/experimental-data-1/experimental-data-1.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/446429/articles/545668/master/file/figures/experimental-data-1/experimental-data-1.csv"
    folder_url: "/users/446429/articles/545668/master/folder/figures/experimental-data-1"
    treatFirstLineAsHeader: true
external-data-url: https://raw.githubusercontent.com/dennisangemi/lab1-dfa/main/exp-1/experimental-data-1.csv
